In [1]:
print("홍성민")

홍성민


In [2]:
print("인하공업전문대학교 컴퓨터시스템과 2학년 홍성민")

인하공업전문대학교 컴퓨터시스템과 2학년 홍성민


In [3]:
#10에서 20사이의 숫함 중 7개를 선택해 출력
#단, 중복이 없어야 함

import random
list_a = []

def test1(list_a):
    while len(list_a) <=6:
        rand_num = random.randint(10,20)
        if rand_num not in list_a:
            list_a.append(rand_num)
    return list_a

# list_a = test1(list_a)
# list_a

In [4]:


a = [1,7,5]
b = [1,3,7]

def num_baseball(a):
    while True:
        strike = 0
        ball = 0
        data2 = getPlayer()

                
        list_a = [a,data2]
        for i in range(len(list_a[0])):
            if list_a[0][i] in list_a[1]:
                flag = 0
                for j in range(len(list_a[1])):
                    if list_a[0][i] == list_a[1][j] and i==j:
                        strike+=1
                        flag = 1
                        break
                if flag ==0:
                    ball+=1
        print("strike :",strike,"ball :", ball)
        if strike == 3:
            print("정답입니다")
            break

In [8]:
def getdata():
    data = []
    while True:
        a = random.randint(0,9)
        if a not in data:
            data.append(a)
            
        if len(data) ==3:
            break
    return data




In [11]:
#0~9사이의 중복없이 3개 선택
def getcom():
    data = getdata()
    return data
#0~9사이의 중복없이 3개 입력받기
def getPlayer():
    data = []
    while len(data) <3:
        print("0~9사이의 값을 입력하시오")
        num = input()
        if num in data:
            print("중복된 숫자입니다. 다시 입력하시오")
        if num not in data:
            print(num,"이 입력되었습니다")
            data.append(num)
            
    print("선택한 숫자는 ",data,"입니다")
    return data 
        
        
#s,b의 개수를 계산하여 return
def game():
    data1 = getdata()
    num_baseball(data1)
    



game()

0~9사이의 값을 입력하시오
1 이 입력되었습니다
0~9사이의 값을 입력하시오
2 이 입력되었습니다
0~9사이의 값을 입력하시오
3 이 입력되었습니다
선택한 숫자는  ['1', '2', '3'] 입니다
strike : 0 ball : 0
0~9사이의 값을 입력하시오


KeyboardInterrupt: Interrupted by user

In [36]:
import numpy as np

def numTest1():
    data = [2,5,6,7]
    print(type(data),data)
    data = np.array(data)
    print(type(data),data)
    print(data.shape)
    
    data2 = [[1,2],[3,4],[5,6]]
    print(type(data2),data2)
    data2 = np.array(data2)
    print(type(data2),data2)
    print(data2.shape)
#numTest1()

def numTest2():
    data = np.random.randint(0,10,(2,3))
    print(type(data),data)
    print(data.shape)
#numTest2()

def numTest3():
    data = np.random.rand(5,3)
    print(data)
    data2 = np.random.rand(5,3,1)
    print(data2)
    
#numTest3()

def numTest4():
    data = np.random.randint(0,100,(30,3))
    print(data)
#numTest4()

def numTest5():
    data = np.random.randint(0,10,(3,4))
    data2 = np.random.randint(10,20,(3,4))
    #print(data.shape,data)
    #print(data2.shape,data2)
    a = data + data2
    b = data - data2
    a_double = a * 2
    print(a)
    print(b)
    print(a_double)
#numTest5()

def test2():
    data1 = np.random.randint(0, 100, (5, 4))
    print(data1, data1.shape)
    
    data2 = data1[:,[0,1]] # 열 자르기
    print(data2)
    data3 = data1[:, [0, 2, 3]]
    print(data3)


In [53]:
import numpy as np

def numTest6():
    data = np.random.randint(0,10,(3,4))
    print(data,data.shape)
    data2 = np.random.randint(0,20,(4,5))
    print(data2,data2.shape)
    
    data3 = data @ data2 # (3,4) @ (4,5) = (3,5)
    print(data3,data3.shape)
    
    data4 = np.dot(data,data2)
    print(data4,data4.shape)

#numTest6()

def test2():
    data1 = np.random.randint(0, 100, (5, 4))
    print(data1, data1.shape)
    
    data2 = data1[:,[0,1]] # 열 자르기
    print(data2)
    data3 = data1[:, [0, 2, 3]]
    print(data3)
    
def test3():
    data = np.random.randint(0,10,(10,5))
    #print(data,data.shape)
    data1 = data[:,:2]
    #print(data1)
    data = np.random.randint(0,10,(10,20))
    print(data)
    data2 = data[:,-4:]
    print(data2)

#test3()

def test4():
    data = np.random.randint(10,20,(100,5))
    print(data,data.shape)
    data1 = data[-20:,:]
    print("----------------")
    print(data1,data1.shape)
    
#test4()

def test5():
    data = np.random.randint(0,10,(10,))
    print(data,data.shape)
    data1 = data.reshape(2,5)
    print(data1,data1.shape)
    
def test6():
    data = np.random.randint(10,20,(20,))
    print(data,data.reshape)
    
    data1 = data.reshape(5,-1)
    print(data1,data1.shape)
#test5()


def test7():
    data = np.random.randint(0,10,(2,5))
    print(data,data.shape)
    print("==================")
    data1 = data.T
    print(data1,data1.shape)
test7()

[[4 8 3 3 2]
 [9 2 6 8 6]] (2, 5)
[[4 9]
 [8 2]
 [3 6]
 [3 8]
 [2 6]] (5, 2)
