In [7]:
import numpy as np
from tensorflow.keras import datasets


np.set_printoptions(linewidth=150,threshold=1000)
(x_train,y_train),(x_test,y_test) = datasets.mnist.load_data()
print(x_test[1])
print(y_train[0])


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 116 125 171 255 255 150  93   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 169 253 253 253 253 253 253 218  30   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 169 253 253 253 213 142 176 253 253 122   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  52 250 253 210  32  12   0   6 206 253 140   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  77 251 210  25   0   0   0 122 248 253  65   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  31  18   0   0   0   0 209 253 253  65   0   

In [8]:
y = np.array([[1,2],[3,4],[5,6]])
y.shape

(3, 2)

In [9]:
x_train.shape

(60000, 28, 28)

In [10]:
x_train = x_train.flatten()
x_train.reshape(x_train,(60000,1,28,28))

TypeError: only integer scalar arrays can be converted to a scalar index