# Day2_1

### Perceptron


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import random

def test1_1():
    x = [[0,0],[0,1],[1,0],[1,1]]
    y = [0,0,0,1]

    w = [random.random(),random.random(),random.random()]
    
    print(w)
    for j in range(50):
        print(j,">"*50)
        for i in range(len(x)):
            #print(x[i])
            net = x[i][0] * w[0] +x[i][1] * w[1] + 1 * w[2]
            
            if net > 0:
                y_pre = 1
            else:
                y_pre = 0
            print("x[i] : ",x[i],"\n net : ",net,'\n y_pre : ',y_pre)
            # w = w + 0.01 * (y - y_pre) * x
            
            
            w[0] = w[0] + 0.01 * (y[i] - y_pre) *x[i][0]
            w[1] = w[1] + 0.01 * (y[i] - y_pre) *x[i][1]
            w[2] = w[2] + 0.01 * (y[i] - y_pre) * 1
                
#test1_1()
def test1_2():
    x = [[0,0],[0,1],[1,0],[1,1]]
    y = [0,1,1,1]
    
    #system parameter = 시스템에서 정의한 값
    #hyper parameter = 사람이 정의한값
    
    w = [random.random(),random.random(),random.random()]
    for epochs in range(50):
        print(epochs,">"*50)
        for i in range(len(x)):
            net = x[i][0] * w[0] +x[i][1] * w[1] + 1 * w[2]
            
            if net > 0:
                act = 1
            else :
                act = 0
                
            loss = y[i] - act
            
            w[0] = w[0] + 0.01*loss *x[i][0]
            w[1] = w[1] + 0.01*loss *x[i][1]
            w[2] = w[2] + 0.01*loss * 1
            print("x[i] : ",x[i],
                    "\n net : ",net,
                    '\n act : ',act,
                    '\n w[0]',w[0],
                    '\n w[1]',w[1],
                    '\n w[2]',w[2])
#test1_2()
    
def test1_3():
    # 신경망 구조는 input = 3, hidden = 6, output = 1
    
    x = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,1]]) #shape = (4,3)
    y = np.array([[0],[1],[1],[0]])
    print(x.shape,y.shape)
    
    weight_0 =np.random.random((3,6)) # 3 * 6
    print(weight_0.shape) 
    weight_1 = np.random.random((6,1)) # 6 * 1
    print(weight_1.shape)
    
    for i in range(100):
        #정방향 계산
        net_1 = x @ weight_0 # (4,3) @ (3,6) = (4,6)
        print(net_1,net_1.shape)
        
        act_1 = 1 / (1 + np.exp(-net_1)) # (4,6)
        print(act_1,act_1.shape)
        
        act_1[:,-1] = 1.0
        net_2 = act_1 @ weight_1
        print(net_2,net_2.shape)
        
        act_2 = 1 / (1 + np.exp(-net_2))
        print(act_2,act_2.shape)
        
        print("="*100)
        
        act_2_error = act_2 - y # (4,1) - (4,1) = error
        t = act_2 * (1 - act_2) # (4,1) * (1 - (4,1)) = (4,1)
        act_2_delta = act_2_error * t
        print(act_2_delta,act_2_delta.shape)
        
        weight_1 = weight_1 - 0.2 * (act_1.T @ act_2_delta) #(6,4) @ (4,1) = (6,1)
        print(weight_1,weight_1.shape)
        
        act_1_error = act_2_delta @ weight_1.T # (4,1) @ (1,6) = (4,6)
        print(act_1_error,act_1_error.shape)
        t = act_1 * (1 - act_1)
        act_1_delta = act_1_error * t
        print(act_1_delta,act_1_delta.shape)
        weight_0 = weight_0 - 0.2 * (x.T @ act_1_delta)
        print(weight_0,weight_0.shape)
        
        print("x :",x,"\t y :",y,
                '\n act_2 : ',act_2)
        
test1_3()
    
    

(4, 3) (4, 1)
(3, 6)
(6, 1)
[[0.         0.         0.         0.         0.         0.        ]
 [0.795253   1.07653818 0.85768901 1.15528653 0.66394166 0.24267525]
 [1.21394086 1.32822864 1.07718335 1.01270094 0.73874312 1.17574116]
 [1.53277151 2.02149238 1.11942189 1.97764702 0.95645056 1.24263874]] (4, 6)
[[0.5        0.5        0.5        0.5        0.5        0.5       ]
 [0.68895814 0.74583831 0.7021776  0.7604752  0.66014527 0.56037282]
 [0.7709955  0.79054748 0.74596059 0.7335484  0.67672095 0.76418119]
 [0.82241146 0.88303524 0.75388147 0.87843011 0.72241059 0.77602299]] (4, 6)
[[1.16164381]
 [1.46397636]
 [1.56158293]
 [1.64158778]] (4, 1)
[[0.76163128]
 [0.8121401 ]
 [0.82658038]
 [0.83775087]] (4, 1)
[[ 0.13827345]
 [-0.02866152]
 [-0.02485888]
 [ 0.11387074]] (4, 1)
[[0.96646962]
 [0.08457861]
 [0.14261761]
 [0.00265771]
 [0.27006319]
 [0.32736244]] (6, 1)
[[ 1.33637093e-01  1.16949769e-02  1.97202297e-02  3.67490816e-04
   3.73425705e-02  4.52655354e-02]
 [-2.77004840e-

# Day2_2

### OpenCV


In [3]:

import cv2

def test1():
    img = cv2.imread("img.jpg")
    print(img.shape)
    
    cv2.imshow("my",img)
    
    cv2.destroyAllWindows()
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    
def test2():
    img = cv2.imread('img.jpg')
    print(img.shape)
    
    img1 = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    print(img1.shape)
    cv2.imshow("gray",img1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.destroyAllWindows()
    
    
#test1()
#test2()

def test3():
    img = cv2.imread("img.jpg")
    print(img.shape)
    w,h,_ = img.shape
    print(w,h)
    
    w = int(w * 0.5)
    h = int(h * 0.5)
    print(w,h)
    img1 = cv2.resize(img,(h,w))
    print(img1.shape)
    cv2.namedWindow("image")
    cv2.imshow('image', img1)
    cv2.waitKey(0) # close window when a key press is detected
    cv2.destroyWindow('image')
    cv2.waitKey(1)
    
#test3()

def test4():
    img = cv2.imread("img.jpg")
    print(img.shape)
    
    cv2.imshow("color",img)
    
    img2 = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    cv2.namedWindow("image")
    cv2.imshow('image', img2)
    cv2.waitKey(0) # close window when a key press is detected
    cv2.destroyWindow('image')
test4()

(390, 640, 3)


: 

In [1]:
import os
import cv2
import numpy as np

def make_data():
    path = "./data"
    file_list = os.listdir(path)
    print(file_list)
    
    data = []
    
    for i in range(len(file_list)):
        file_path = path + "/" + file_list[i]
        print(file_path)
        try:
            img = cv2.imread(file_path,0)
            img = cv2.resize(img,(320,240))
        except Exception as e:
            print(str(e))
            
        #print(file_path,img.shape)
    
        data.append(img)
        
    data = np.array(data)
    print(data.shape)
    return data
make_data()


['my1.h5', 'fish1.jpg', 'fish3.jpg', 'fish2.jpg', 'fish5.jpg', 'fish4.jpg']
./data/my1.h5
OpenCV(4.5.2) ../modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

./data/fish1.jpg
./data/fish3.jpg
./data/fish2.jpg
./data/fish5.jpg
./data/fish4.jpg
(6,)


/var/folders/xl/l17__8q55nsdyt859lgd1nvc0000gn/T/ipykernel_3509/1872531573.py:25: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array(data)


array([None, array([[255, 255, 255, ..., 255, 255, 255],
                    [255, 255, 255, ..., 255, 255, 255],
                    [255, 255, 255, ..., 255, 255, 255],
                    ...,
                    [255, 255, 255, ..., 255, 255, 255],
                    [255, 255, 255, ..., 255, 255, 255],
                    [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
       array([[255, 255, 255, ..., 248, 252, 252],
              [255, 255, 255, ..., 248, 251, 251],
              [255, 255, 255, ..., 248, 250, 252],
              ...,
              [255, 255, 255, ..., 255, 255, 255],
              [255, 255, 255, ..., 255, 255, 255],
              [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
       array([[255, 255, 255, ..., 255, 255, 255],
              [255, 255, 255, ..., 255, 255, 255],
              [255, 255, 255, ..., 255, 255, 255],
              ...,
              [255, 255, 255, ..., 255, 255, 255],
              [255, 255, 255, ..., 255, 255, 255],
    

In [2]:
import numpy as np

import tensorflow as tf
import cv2
from tensorflow.keras import datasets
from tensorflow.keras import models, layers



2.9.2


In [5]:
def getData():
  (x_train,y_train),(x_test,y_test) = datasets.mnist.load_data()
  x_train = x_train.reshape(-1,28 * 28)
  print(x_train.shape)

  x_test = x_test.reshape(-1,28*28)
  print(x_test.shape)

  return (x_train,y_train),(x_test,y_test)
#getData()

def makeModel(): # input = 1차원리스트 (28*28, )
                 # output = 1차원리스트 (10, )


  model = models.Sequential()
  model.add(layers.Dense(200, activation="relu",input_shape=(28 * 28, )))
  model.add(layers.Dense(100, activation='relu',input_shape=(28 * 28, )))
  model.add(layers.Dense(10, activation='softmax'))

  model.compile(loss = "sparse_categorical_crossentropy",
                optimizer="Adam",
                metrics = ["accuracy"])
  print(model.summary())
  return model
#makeModel() 

def doLearn():
  (x_train,y_train),(x_test,y_test) = getData()
  model = makeModel()
  log = model.fit(x_train,y_train,epochs=2,batch_size = 16)

  model.save('my1.h5')
doLearn()

11490434/11490434 [==============================] - 1s 0us/step
(60000, 784)
(10000, 784)
Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-06-29 09:17:36.161171: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-29 09:17:36.163262: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 200)               157000    
                                                                 
 dense_1 (Dense)             (None, 100)               20100     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 178,110
Trainable params: 178,110
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/2


2022-06-29 09:17:36.890546: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-06-29 09:17:37.103868: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


3750/3750 [==============================] - 18s 4ms/step - loss: 1.0998 - accuracy: 0.8608
Epoch 2/2
3750/3750 [==============================] - 16s 4ms/step - loss: 0.2457 - accuracy: 0.9351


In [6]:
def getData():
    (x_train,y_train),(x_test,y_test) = datasets.mnist.load_data()
    x_train = x_train.reshape(-1,28 * 28)
    x_test = x_test.reshape(-1,28 * 28)

    return (x_train,y_train),(x_test,y_test)

def makeModel():

  model = models.Sequential()
  model.add(layers.Dense(1000,activation = "relu",input_shape = (28 * 28, )))
  model.add(layers.Dense(500,activation = "relu"))
  model.add(layers.Dense(10,activation = "softmax"))

  model.compile(loss = "sparse_categorical_crossentropy",
                optimizer = "Adam",
                metrics = ["accuracy"])
  print(model.summary())
  return model
#makeModel()
def doLearn():
  (x_train,y_train),(x_test,y_test) = getData()
  model = makeModel()

  log = model.fit(x_train,y_train,
                  epochs=2,
                  batch_size=16)
  
  model.save("my2.h5")
  score = model.evaluate(x_test,y_test)
  print(score)

  lossH = log.history["loss"]
  accuracyH = log.history["accuracy"]
  print("lossH : ",lossH,
        "\n accuracyH",accuracyH)

doLearn()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1000)              785000    
                                                                 
 dense_4 (Dense)             (None, 500)               500500    
                                                                 
 dense_5 (Dense)             (None, 10)                5010      
                                                                 
Total params: 1,290,510
Trainable params: 1,290,510
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/2
  18/3750 [..............................] - ETA: 23s - loss: 82.4087 - accuracy: 0.4410 

2022-06-29 09:18:46.769292: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


3750/3750 [==============================] - 20s 5ms/step - loss: 1.1530 - accuracy: 0.9052
Epoch 2/2
 12/313 [>.............................] - ETA: 1s - loss: 0.3326 - accuracy: 0.9375  

2022-06-29 09:19:26.370634: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


313/313 [==============================] - 1s 4ms/step - loss: 0.3054 - accuracy: 0.9296
[0.30535978078842163, 0.9296000599861145]
lossH :  [1.1530277729034424, 0.23991648852825165] 
 accuracyH [0.9051833152770996, 0.938533365726471]
