## 인공신경망

### and 게이트 구현

In [57]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [34]:
x = [[0,0],[0,1],[1,0],[1,1]]
y = [0,0,0,1]

# 가중치
w = [random.random(), random.random(), random.random()]

for j in range(50):
  print(f'{j}번째 ============================>')
  for i  in range(len(x)):
    # x 첫번째, 두번째, 절편값
    net = x[i][0] *w[0] + x[i][1]*w[1] + 1*w[2]
    
    if net > 0 :
      y_pre = 1
    else : 
      y_pre = 0
    
    print(f'x값:{x[i]}   오류: {net}   y예측값: {y_pre}')
    # w = w+0.01*(y-y_pre)*x
    # 가중치 = 원래 값에 에러(y_pre)만큼을 더해서 w(가중치를) 업데이트
    w[0] = w[0] + 0.01*(y[i] - y_pre)*x[i][0]
    w[1] = w[1] + 0.01*(y[i] - y_pre)*x[i][1]
    w[2] = w[2] + 0.01*(y[i] - y_pre)*1
  

0번째 ============================>
x값:[0, 0]   오류: 0.24874537272730535   y예측값: 1
x값:[0, 1]   오류: 1.1922291529159743   y예측값: 1
x값:[1, 0]   오류: 0.7510832455109722   y예측값: 1
x값:[1, 1]   오류: 1.6745670256996408   y예측값: 1
1번째 ============================>
x값:[0, 0]   오류: 0.21874537272730532   y예측값: 1
x값:[0, 1]   오류: 1.1522291529159743   y예측값: 1
x값:[1, 0]   오류: 0.7110832455109721   y예측값: 1
x값:[1, 1]   오류: 1.624567025699641   y예측값: 1
2번째 ============================>
x값:[0, 0]   오류: 0.1887453727273053   y예측값: 1
x값:[0, 1]   오류: 1.1122291529159742   y예측값: 1
x값:[1, 0]   오류: 0.6710832455109721   y예측값: 1
x값:[1, 1]   오류: 1.5745670256996407   y예측값: 1
3번째 ============================>
x값:[0, 0]   오류: 0.15874537272730527   y예측값: 1
x값:[0, 1]   오류: 1.0722291529159742   y예측값: 1
x값:[1, 0]   오류: 0.6310832455109721   y예측값: 1
x값:[1, 1]   오류: 1.5245670256996409   y예측값: 1
4번째 ============================>
x값:[0, 0]   오류: 0.12874537272730524   y예측값: 1
x값:[0, 1]   오류: 1.0322291529159742   y예측값: 1
x값:[1, 0]   오류: 0

### OR 논리 게이트 구현

In [53]:

x = [[0,0],[0,1],[1,0],[1,1]]
y = [0,1,1,1]

#system parameter = 시스템에서 정의한 값
#hyper parameter = 사람이 정의한값

w = [random.random(),random.random(),random.random()]k
for epoch in range(50):
    print(epoch, "==============")
    for i in range(len(x)):
        # 예측하기
        net = x[i][0] * w[0] +x[i][1] * w[1] + 1 * w[2]
        
        if net > 0:
            act = 1
        else :
            act = 0
        
        # 손실 = 원래 y값 - 예측한 y값
        loss = y[i] - act
        
        # 가중치 업데이트
        # 원래 가중치 + lr* loss * x값
        w[0] = w[0] + 0.01*loss *x[i][0]
        w[1] = w[1] + 0.01*loss *x[i][1]
        w[2] = w[2] + 0.01*loss * 1
        print(f'x값:{x[i]}   y값: {y[i]}   y예측값: {y_pre}')

0 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
1 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
2 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
3 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
4 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
5 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
6 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값: 1
x값:[1, 1]   y값: 1   y예측값: 1
7 ==============
x값:[0, 0]   y값: 0   y예측값: 1
x값:[0, 1]   y값: 1   y예측값: 1
x값:[1, 0]   y값: 1   y예측값

### 경사하강법 - 순전파 및 역전파 구현

In [77]:
x = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([[0],[1],[1],[0]])


w0 = np.random.random((3,6))
w1 = np.random.random((6,1))

for i in range(50) :
  net1 = x@w0  # (4,3) @ (3,6) = (4,6)

  act1 = 1 / (1+np.exp(-net1)) # 시그모이드
  act1[:, -1] = 1.0

  net2 = act1 @ w1 # (4,6) @ (6,1) = (4,1)

  act2 = 1/(1+np.exp(-net2))

  # 순전파
  # loss 
  act2_err =  act2 -  y # (4,1) - (4,1)
  diff = act2 * (1-act2) 
  act2_diff = act2_err * diff

  # 가중치 업데이트
  w1 = w1 - 0.2*(act1.T@act2_diff) # (4,6).T -> (6.4) @ (4,1)

  # 역전파
  # loss
  act1_err = act2_diff @ w1.T # (4,1) @ (1,6) = (4,6)
  diif = act1 *(1-act1)
  act1_diff = act1_err * diff # (4,6) * (4,6)

  # 가중치 없데이트 
  w0 = w0 - 0.2*(x.T @ act1_diff) 

  print(f'에포크 {i}========= \n {act2}')


에포크 0========= 
 [[0.82251966]
 [0.84177845]
 [0.85089376]
 [0.86346621]]
에포크 1========= 
 [[0.80504734]
 [0.82420855]
 [0.83361976]
 [0.8463719 ]]
에포크 2========= 
 [[0.78567214]
 [0.80449478]
 [0.81414052]
 [0.82692233]]
에포크 3========= 
 [[0.76449815]
 [0.78270177]
 [0.79249724]
 [0.80512008]]
에포크 4========= 
 [[0.74180286]
 [0.7590861 ]
 [0.76892577]
 [0.78117209]]
에포크 5========= 
 [[0.71805768]
 [0.73412784]
 [0.74389325]
 [0.7555362 ]]
에포크 6========= 
 [[0.69390556]
 [0.70851414]
 [0.71808652]
 [0.72891707]]
에포크 7========= 
 [[0.67008642]
 [0.68306118]
 [0.69233597]
 [0.70219064]]
에포크 8========= 
 [[0.64732533]
 [0.65858866]
 [0.66748758]
 [0.67626792]]
에포크 9========= 
 [[0.62622092]
 [0.6357892 ]
 [0.64426633]
 [0.65194422]]
에포크 10========= 
 [[0.60717319]
 [0.61513981]
 [0.62318063]
 [0.62978974]]
에포크 11========= 
 [[0.59036818]
 [0.59687807]
 [0.60449353]
 [0.6101122 ]]
에포크 12========= 
 [[0.57580937]
 [0.58103353]
 [0.5882519 ]
 [0.59298426]]
에포크 13========= 
 [[0.56337156]
 [0