## numpy

### 파이썬 기초

In [148]:
import random

def getcom():
  a = [ ]
  for b in range(3):
    b = random.randint(10,20)
    while b in a:
      b = random.randint(10,20)
    a.append(b)


def getplayer():
  a = []
  for b in range(3):
    b = int(input("0~9 사이 값을 입력:"))
    while b in a:
      b = int(input("중복입니다 0~9 사이 값을 입력:"))
    a.append(b)



def getsb(com, player):
  while True:
    strike = 0
    ball = 0


            
    list_a = [com,player]
    for i in range(len(list_a[0])):
        if list_a[0][i] in list_a[1]:
            flag = 0
            for j in range(len(list_a[1])):
                if list_a[0][i] == list_a[1][j] and i==j:
                    strike+=1
                    flag = 1
                    break
            if flag ==0:
                ball+=1
    print("strike :",strike,"ball :", ball)
    if strike == 3:
        print("정답입니다")
        break



def game():
  com = getcom()
  for i in range(5):
    player = getplayer()
    s,b = getsb(com, player)
    print(f"스트라이크 : {s}  볼 : {b}")
    
    if (s == 3):
      print("이김", com)
      return
    print("짐", com)

game()

TypeError: object of type 'NoneType' has no len()

### 넘파이 배열 기초

In [187]:
import numpy as np

def test1():
  data = [1,2,3,4]
  data = np.array(data)
  print(type(data), data)

  data1 = ([1,2,3],
  [1,2,3],
  [1,2,3])
  print(data1)
test1()

def test2():
  # 파라미터 어디서,어디까지, 몇개
  data = np.random.randint(0,10,(10,))
  data1 = np.random.randint(0,10,(2,3))
  print(type(data), data)
  print(type(data1), data1)
test2()

def test3():
  data1 = np.random.rand(5,3,1)
  # print(type(data1), data1)
  data2 = np.random.randn(5,3,1)
  # print(type(data2), data2)

np.random.seed(3)
def test4():
  data = np.random.randint(0,100, (30,3))
  for i in range(len(data)):
    print(data[i])
  # 행, 열
  kor = data[0][0]
  # print("국어점수",kor)

  kor = data[0,0]
  # print("국어점수",kor)
test4()

def test5():
  data1 = np.random.randint(0,10,(3,4))
  print(type(data1), data1)
  data2 = np.random.randint(10,20,(3,4))
  # print(type(data2), data2)
  c = data1 *2
  print(type(c), c)
test5()

<class 'numpy.ndarray'> [1 2 3 4]
([1, 2, 3], [1, 2, 3], [1, 2, 3])
<class 'numpy.ndarray'> [1 8 8 7 0 0 9 1 7 8]
<class 'numpy.ndarray'> [[7 4 0]
 [0 4 3]]
[24  3 56]
[72  0 21]
[19 74 41]
[10 21 38]
[96 20 44]
[93 39 14]
[26 81 90]
[22 66  2]
[63 60  1]
[51 90 69]
[97 29 24]
[62  7 43]
[33 79 48]
[37 20 94]
[49 21 78]
[28 54  0]
[64 18 63]
[37 56 56]
[71 37 46]
[33  1 85]
[74 99 91]
[16 80 32]
[16 18 75]
[55 96 95]
[13 37 30]
[48 61 33]
[52  2 28]
[36 90 44]
[48 59 74]
[54 91 21]
<class 'numpy.ndarray'> [[1 8 8 7]
 [0 0 9 1]
 [7 8 7 4]]
<class 'numpy.ndarray'> [[ 2 16 16 14]
 [ 0  0 18  2]
 [14 16 14  8]]


In [204]:
def test():
  data1 = np.random.randint(0,10,(3,4))
  data2 = np.random.randint(10,20,(4,5))
  # 내적 계산
  # (3, 4) @ (4, 5) = (3, 5) / (,4) (4,) 위치부분 같이야 함 / 내적 계산
  data3 = data1 @ data2
  data4 = np.dot(data1, data2)
# test()

def test2():
    data1 = np.random.randint(0, 100, (5, 4))
    print(data1, data1.shape)
    
    data2 = data1[:,[0,1]] # 열 자르기
    print(data2)
    data3 = data1[:, [0, 2, 3]]
    print(data3)
# test2()

def test3():
    data = np.random.randint(0, 10, (10, 5))
    print(data, data.shape)
    
    data1 = data[:, :3]
    print(data1)
    
    data = np.random.randint(0, 14, (10, 20))
    print(data, data.shape)
    
    data1 = data[:, -4:]
    print(data1)
# test3()

def test4():
    data = np.random.randint(10, 20, (100, 5))
    print(data, data.shape)
    
    print('----------------------------------')
    data1 = data[:40, :]
    print(data1)
    
    print('----------------------------------')
    data2 = data[-20:, :]
    print(data2)
# test4()

def test5(): # 차원 변경
    data = np.random.randint(0, 10, (10, ))
    print(data, data.shape)
    
    data1 = data.reshape(2, 5)
    print(data1, data1.shape)
    
    print('----------------------------------')
    data = np.random.randint(10, 20, (20, ))
    print(data, data.shape)
    
    data1 = data.reshape(5, -1) # -1는 자동으로 맞춰줌
    print(data1, data1.shape)
# test5()


10
