In [1]:
print("홍성민")

홍성민


In [2]:
print("인하공업전문대학교 컴퓨터시스템과 2학년 홍성민")

인하공업전문대학교 컴퓨터시스템과 2학년 홍성민


In [3]:
#10에서 20사이의 숫함 중 7개를 선택해 출력
#단, 중복이 없어야 함

import random
list_a = []

def test1(list_a):
    while len(list_a) <=6:
        rand_num = random.randint(10,20)
        if rand_num not in list_a:
            list_a.append(rand_num)
    return list_a

# list_a = test1(list_a)
# list_a

In [4]:


a = [1,7,5]
b = [1,3,7]

def num_baseball(a):
    while True:
        strike = 0
        ball = 0
        data2 = getPlayer()

                
        list_a = [a,data2]
        for i in range(len(list_a[0])):
            if list_a[0][i] in list_a[1]:
                flag = 0
                for j in range(len(list_a[1])):
                    if list_a[0][i] == list_a[1][j] and i==j:
                        strike+=1
                        flag = 1
                        break
                if flag ==0:
                    ball+=1
        print("strike :",strike,"ball :", ball)
        if strike == 3:
            print("정답입니다")
            break

In [8]:
def getdata():
    data = []
    while True:
        a = random.randint(0,9)
        if a not in data:
            data.append(a)
            
        if len(data) ==3:
            break
    return data




In [11]:
#0~9사이의 중복없이 3개 선택
def getcom():
    data = getdata()
    return data
#0~9사이의 중복없이 3개 입력받기
def getPlayer():
    data = []
    while len(data) <3:
        print("0~9사이의 값을 입력하시오")
        num = input()
        if num in data:
            print("중복된 숫자입니다. 다시 입력하시오")
        if num not in data:
            print(num,"이 입력되었습니다")
            data.append(num)
            
    print("선택한 숫자는 ",data,"입니다")
    return data 
        
        
#s,b의 개수를 계산하여 return
def game():
    data1 = getdata()
    num_baseball(data1)
    



game()

0~9사이의 값을 입력하시오
1 이 입력되었습니다
0~9사이의 값을 입력하시오
2 이 입력되었습니다
0~9사이의 값을 입력하시오
3 이 입력되었습니다
선택한 숫자는  ['1', '2', '3'] 입니다
strike : 0 ball : 0
0~9사이의 값을 입력하시오


KeyboardInterrupt: Interrupted by user

In [36]:
import numpy as np

def numTest1():
    data = [2,5,6,7]
    print(type(data),data)
    data = np.array(data)
    print(type(data),data)
    print(data.shape)
    
    data2 = [[1,2],[3,4],[5,6]]
    print(type(data2),data2)
    data2 = np.array(data2)
    print(type(data2),data2)
    print(data2.shape)
#numTest1()

def numTest2():
    data = np.random.randint(0,10,(2,3))
    print(type(data),data)
    print(data.shape)
#numTest2()

def numTest3():
    data = np.random.rand(5,3)
    print(data)
    data2 = np.random.rand(5,3,1)
    print(data2)
    
#numTest3()

def numTest4():
    data = np.random.randint(0,100,(30,3))
    print(data)
#numTest4()

def numTest5():
    data = np.random.randint(0,10,(3,4))
    data2 = np.random.randint(10,20,(3,4))
    #print(data.shape,data)
    #print(data2.shape,data2)
    a = data + data2
    b = data - data2
    a_double = a * 2
    print(a)
    print(b)
    print(a_double)
#numTest5()

def test2():
    data1 = np.random.randint(0, 100, (5, 4))
    print(data1, data1.shape)
    
    data2 = data1[:,[0,1]] # 열 자르기
    print(data2)
    data3 = data1[:, [0, 2, 3]]
    print(data3)


In [53]:
import numpy as np

def numTest6():
    data = np.random.randint(0,10,(3,4))
    print(data,data.shape)
    data2 = np.random.randint(0,20,(4,5))
    print(data2,data2.shape)
    
    data3 = data @ data2 # (3,4) @ (4,5) = (3,5)
    print(data3,data3.shape)
    
    data4 = np.dot(data,data2)
    print(data4,data4.shape)

#numTest6()

def test2():
    data1 = np.random.randint(0, 100, (5, 4))
    print(data1, data1.shape)
    
    data2 = data1[:,[0,1]] # 열 자르기
    print(data2)
    data3 = data1[:, [0, 2, 3]]
    print(data3)
    
def test3():
    data = np.random.randint(0,10,(10,5))
    #print(data,data.shape)
    data1 = data[:,:2]
    #print(data1)
    data = np.random.randint(0,10,(10,20))
    print(data)
    data2 = data[:,-4:]
    print(data2)

#test3()

def test4():
    data = np.random.randint(10,20,(100,5))
    print(data,data.shape)
    data1 = data[-20:,:]
    print("----------------")
    print(data1,data1.shape)
    
#test4()

def test5():
    data = np.random.randint(0,10,(10,))
    print(data,data.shape)
    data1 = data.reshape(2,5)
    print(data1,data1.shape)
    
def test6():
    data = np.random.randint(10,20,(20,))
    print(data,data.reshape)
    
    data1 = data.reshape(5,-1)
    print(data1,data1.shape)
#test5()


def test7():
    data = np.random.randint(0,10,(2,5))
    print(data,data.shape)
    print("==================")
    data1 = data.T
    print(data1,data1.shape)
test7()

[[4 8 3 3 2]
 [9 2 6 8 6]] (2, 5)
[[4 9]
 [8 2]
 [3 6]
 [3 8]
 [2 6]] (5, 2)


In [58]:
import numpy as np
np.random.seed(20)

def test3_1():
    data = np.random.randint(0,10,(10,))
    print(data,data.shape)
    print("----------------------------")
    
    data1 = data[data>5]
    print(data1,data1.shape)
    data2 = data[data>7]
    print(data2,data2.shape)
    data3 = data[data != 5]
    print(data3,data3.shape)
    
#test3_1()

def test3_2():
    data = np.random.randint(0,10,(5,3))
    print(data,data.shape)
    print("===========================")
    data1 = data[1:,]
    #print(data1,data1.shape)
    
    data2 = data1[data1>5]
    
    print(data2,data2.shape)

#test3_2()

def test3_3():
    data = np.random.randint(0,10,(10,))
    print(data,data.shape)
    print("===========================")
    
    data1 = np.where(data>5,1,0)
    print(data1,data1.shape)

#test3_3()


def check_BMI():
    data_w = np.array([86,74,59,95,80,68,60])
    data_h = np.array([1.83,1.76,1.69,1.77,1.78,1.60,1.90])
    
    bmi =data_w/data_h **2
    data = np.where(bmi > 27,"비만","정상")
    print(data)
    print(bmi)
#check_BMI()

#30명의 회원이 있다. 학생들은 3개의 평가를 받았다. 학생의 평균 값을 구하라
#과목 평균을 출력

import pandas as pd


def avg_student():
    data = np.random.randint(0,100,(30,3))
    df = pd.DataFrame(data,columns=["kor","eng","mat"])
    kor_avg = data[:,0]
    kor_avg = sum(kor_avg)//30
    eng_avg = data[:,1]
    eng_avg = sum(eng_avg)//30
    mat_avg = data[:,1]
    mat_avg = sum(mat_avg)//30
    
    for i in range(30):
        df.loc[i,"tot"] = sum(data[i,:])
        df.loc[i,"avg"] = df.loc[i,"tot"]//3
    print(df)
    print(kor_avg,": 국어 전체 평균")
    print(eng_avg,": 영어 전체 평균")
    print(mat_avg,": 수학 전체 평균")
    # data_avg = data[:,:]
    
avg_student()

    kor  eng  mat    tot   avg
0    99   90   15  204.0  68.0
1    95   28   90  213.0  71.0
2     9   20   75  104.0  34.0
3    22   71   34  127.0  42.0
4    96   40   85  221.0  73.0
5    90   26   83  199.0  66.0
6    16   62   16   94.0  31.0
7     7   98    6  111.0  37.0
8    26   13   75  114.0  38.0
9    58   25    3   86.0  28.0
10   74   75   61  210.0  70.0
11   77   83   57  217.0  72.0
12   94   32   10  136.0  45.0
13    6   75   18   99.0  33.0
14    3   77   17   97.0  32.0
15   43   16   18   77.0  25.0
16   79   90   59  228.0  76.0
17   71   75   29  175.0  58.0
18   45    6   63  114.0  38.0
19   78   24   18  120.0  40.0
20   93   33   78  204.0  68.0
21   42   94    3  139.0  46.0
22   18   70   52  140.0  46.0
23   22   14    4   40.0  13.0
24   27   75    8  110.0  36.0
25    6   26   79  111.0  37.0
26   82   78   10  170.0  56.0
27   33   85   17  135.0  45.0
28   40   82   42  164.0  54.0
29   60   84   30  174.0  58.0
50 : 국어 전체 평균
55 : 영어 전체 평균
55 : 수학 전체 