# Day2_1

### Perceptron


In [44]:
import numpy as np
import matplotlib.pyplot as plt
import random

def test1_1():
    x = [[0,0],[0,1],[1,0],[1,1]]
    y = [0,0,0,1]

    w = [random.random(),random.random(),random.random()]
    
    print(w)
    for j in range(50):
        print(j,">"*50)
        for i in range(len(x)):
            #print(x[i])
            net = x[i][0] * w[0] +x[i][1] * w[1] + 1 * w[2]
            
            if net > 0:
                y_pre = 1
            else:
                y_pre = 0
            print("x[i] : ",x[i],"\n net : ",net,'\n y_pre : ',y_pre)
            # w = w + 0.01 * (y - y_pre) * x
            
            
            w[0] = w[0] + 0.01 * (y[i] - y_pre) *x[i][0]
            w[1] = w[1] + 0.01 * (y[i] - y_pre) *x[i][1]
            w[2] = w[2] + 0.01 * (y[i] - y_pre) * 1
                
#test1_1()
def test1_2():
    x = [[0,0],[0,1],[1,0],[1,1]]
    y = [0,1,1,1]
    
    #system parameter = 시스템에서 정의한 값
    #hyper parameter = 사람이 정의한값
    
    w = [random.random(),random.random(),random.random()]
    for epochs in range(50):
        print(epochs,">"*50)
        for i in range(len(x)):
            net = x[i][0] * w[0] +x[i][1] * w[1] + 1 * w[2]
            
            if net > 0:
                act = 1
            else :
                act = 0
                
            loss = y[i] - act
            
            w[0] = w[0] + 0.01*loss *x[i][0]
            w[1] = w[1] + 0.01*loss *x[i][1]
            w[2] = w[2] + 0.01*loss * 1
            print("x[i] : ",x[i],
                    "\n net : ",net,
                    '\n act : ',act,
                    '\n w[0]',w[0],
                    '\n w[1]',w[1],
                    '\n w[2]',w[2])
#test1_2()
    
def test1_3():
    # 신경망 구조는 input = 3, hidden = 6, output = 1
    
    x = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,1]]) #shape = (4,3)
    y = np.array([[0],[1],[1],[0]])
    print(x.shape,y.shape)
    
    weight_0 =np.random.random((3,6)) # 3 * 6
    print(weight_0.shape) 
    weight_1 = np.random.random((6,1)) # 6 * 1
    print(weight_1.shape)
    
    for i in range(100):
        #정방향 계산
        net_1 = x @ weight_0 # (4,3) @ (3,6) = (4,6)
        print(net_1,net_1.shape)
        
        act_1 = 1 / (1 + np.exp(-net_1)) # (4,6)
        print(act_1,act_1.shape)
        
        act_1[:,-1] = 1.0
        net_2 = act_1 @ weight_1
        print(net_2,net_2.shape)
        
        act_2 = 1 / (1 + np.exp(-net_2))
        print(act_2,act_2.shape)
        
        print("="*100)
        
        act_2_error = act_2 - y # (4,1) - (4,1) = error
        t = act_2 * (1 - act_2) # (4,1) * (1 - (4,1)) = (4,1)
        act_2_delta = act_2_error * t
        print(act_2_delta,act_2_delta.shape)
        
        weight_1 = weight_1 - 0.2 * (act_1.T @ act_2_delta) #(6,4) @ (4,1) = (6,1)
        print(weight_1,weight_1.shape)
        
        act_1_error = act_2_delta @ weight_1.T # (4,1) @ (1,6) = (4,6)
        print(act_1_error,act_1_error.shape)
        t = act_1 * (1 - act_1)
        act_1_delta = act_1_error * t
        print(act_1_delta,act_1_delta.shape)
        weight_0 = weight_0 - 0.2 * (x.T @ act_1_delta)
        print(weight_0,weight_0.shape)
        
        print("x :",x,"\t y :",y,
                '\n act_2 : ',act_2)
        
test1_3()
    
    

(4, 3) (4, 1)
(3, 6)
(6, 1)
[[0.         0.         0.         0.         0.         0.        ]
 [0.90459151 1.37630337 1.05466232 1.11887913 0.89264494 0.6412882 ]
 [0.95529493 1.08494702 1.44235918 1.07379777 0.6004208  0.50213045]
 [1.17124505 1.78643001 2.04893965 1.20128217 1.39688017 0.70721964]] (4, 6)
[[0.5        0.5        0.5        0.5        0.5        0.5       ]
 [0.71189215 0.79839665 0.74166919 0.75378075 0.70943569 0.6550446 ]
 [0.72217878 0.74742902 0.80881972 0.74531848 0.64575257 0.62295986]
 [0.76336999 0.85648903 0.88584043 0.7687528  0.80168835 0.66978651]] (4, 6)
[[2.19288064]
 [2.99191097]
 [2.91026539]
 [3.19855782]] (4, 1)
[[0.89960837]
 [0.95220735]
 [0.94835156]
 [0.96077997]] (4, 1)
[[ 0.08124647]
 [-0.00217497]
 [-0.00252979]
 [ 0.03620394]] (4, 1)
[[0.7067978 ]
 [0.87251923]
 [0.20530854]
 [0.59081129]
 [0.82665268]
 [0.53595423]] (6, 1)
[[ 0.05742483  0.07088911  0.01668059  0.04800133  0.06716261  0.04354439]
 [-0.00153727 -0.00189771 -0.00044654 -0.

# Day2_2

### OpenCV


In [2]:

import cv2

def test1():
    img = cv2.imread("img.jpg")
    print(img.shape)
    
    cv2.imshow("my",img)
    
    cv2.destroyAllWindows()
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    
def test2():
    img = cv2.imread('img.jpg')
    print(img.shape)
    
    img1 = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    print(img1.shape)
    cv2.imshow("gray",img1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.waitKey(1)
    cv2.destroyAllWindows()
    
    
#test1()
#test2()

def test3():
    img = cv2.imread("img.jpg")
    print(img.shape)
    w,h,_ = img.shape
    print(w,h)
    
    w = int(w * 0.5)
    h = int(h * 0.5)
    print(w,h)
    img1 = cv2.resize(img,(h,w))
    print(img1.shape)
    cv2.namedWindow("image")
    cv2.imshow('image', img1)
    cv2.waitKey(0) # close window when a key press is detected
    cv2.destroyWindow('image')
    cv2.waitKey(1)
    
#test3()

def test4():
    img = cv2.imread("img.jpg")
    print(img.shape)
    
    cv2.imshow("color",img)
    
    img2 = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    cv2.namedWindow("image")
    cv2.imshow('image', img2)
    cv2.waitKey(0) # close window when a key press is detected
    cv2.destroyWindow('image')
test4()

(390, 640, 3)


: 

In [ ]:
import os

def make_data():
    path = "./data"
    file_list = os.listdir(path)