In [2]:

import numpy as np
import os
import cv2
from tensorflow.keras import applications, models, layers

print(os.listdir("/Users/hongseongmin/Desktop/data_image/"))

['.DS_Store', 'non', 'seungmin']


In [152]:

def getData():
    path = "/Users/hongseongmin/Desktop/data_image"

    x = []
    y = []
    dir_list = os.listdir(path)
    for i in range(len(dir_list)-1):
        dir_path = path + "/" + dir_list[i+1]
        dir_name = os.listdir(dir_path)

        for j in range(len(dir_name)):
            full_dir_path = dir_path + "/" + dir_name[j]

            img = cv2.imread(full_dir_path)
            img = cv2.resize(img, (32,32))
            x.append(img)
            y.append(i)
    print(x)
    print(y)
    return np.array(x),np.array(y)



In [169]:

def make_model() :
    resnet50 = applications.resnet50.ResNet50(include_top=False, weights="imagenet", input_shape=(32,32,3))
    resnet50.trainable = False
    model = models.Sequential()
    model.add(resnet50)
    model.add(layers.Flatten())
    model.add(layers.Dense(1024, activation="relu"))
    model.add(layers.Dense(512, activation="relu"))

    # 분류 데이터가 몇종류인지
    model.add(layers.Dense(2, activation="softmax"))
    model.compile(loss = "sparse_categorical_crossentropy", optimizer="adam", metrics = ["accuracy"])
    print(model.summary())
    return model

In [170]:


def getTest():
    test_path = "/Users/hongseongmin/Desktop/test/non/test17.png"
    
    test_img = cv2.imread(test_path)
    print(test_img)
    test_img = cv2.resize(test_img, (32,32))
    #test_img = test_img.reshape(32,32,3)
    test_list = []
    test_list.append(test_img)
    test_list = np.array(test_list)
    print(test_img.shape)
    cv2.imwrite("test123.png",test_img)
#getTest()
    return test_list


In [171]:
def learning() :
    (x_train, y_train)= getData()
    model = make_model()
    print("x_train : ",x_train[0])
    print("x_train.shape : ",x_train[0].shape)
    log = model.fit(x_train, y_train, epochs=2, batch_size=16)
    model.save("face.h5")
    (x_test,y_test) = getTestData()
    model.evaluate(x_test,y_test)
learning()

[array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [205, 192, 176],
        [187, 179, 169],
        [172, 167, 162]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [190, 183, 172],
        [180, 173, 167],
        [161, 157, 155]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [183, 177, 172],
        [165, 161, 159],
        [147, 145, 144]],

       ...,

       [[ 20,  47,  68],
        [ 11,  35,  51],
        [ 18,  34,  47],
        ...,
        [ 80, 105, 121],
        [ 91, 122, 137],
        [ 75, 103, 121]],

       [[ 23,  42,  59],
        [ 30,  48,  63],
        [ 15,  30,  43],
        ...,
        [102, 130, 146],
        [121, 148, 163],
        [ 93, 119, 137]],

       [[ 54,  75,  82],
        [ 67,  89,  98],
        [ 39,  53,  64],
        ...,
        [130, 157, 172],
        [104, 129, 148],
        [103, 127, 145]

2022-06-30 00:06:38.836331: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


79/79 [==============================] - 8s 46ms/step - loss: 0.1305 - accuracy: 0.9699
Epoch 2/2
79/79 [==============================] - 2s 27ms/step - loss: 0.0123 - accuracy: 0.9984
[array([[[103, 117, 131],
        [107, 122, 132],
        [109, 124, 134],
        ...,
        [220, 214, 206],
        [230, 221, 208],
        [242, 225, 212]],

       [[104, 119, 130],
        [109, 123, 134],
        [110, 125, 136],
        ...,
        [216, 210, 202],
        [228, 217, 207],
        [235, 221, 209]],

       [[103, 117, 130],
        [103, 118, 129],
        [108, 122, 133],
        ...,
        [216, 209, 203],
        [225, 215, 205],
        [232, 220, 208]],

       ...,

       [[ 84, 101, 112],
        [ 81,  99, 109],
        [ 83, 100, 111],
        ...,
        [ 38,  43,  58],
        [ 71,  78,  97],
        [ 70,  77,  96]],

       [[ 78,  94, 107],
        [ 79,  96, 107],
        [ 79,  95, 106],
        ...,
        [ 39,  43,  60],
        [ 83,  91, 107],
  

2022-06-30 00:06:57.850078: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


13/13 [==============================] - 9s 249ms/step - loss: 0.4915 - accuracy: 0.9267


In [9]:
import cv2
import numpy as np
path = "../tracking/test0.png"

img = cv2.imread(path, cv2.IMREAD_COLOR)



    # 이미지 색 바꾸기

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_ycrcb = cv2.cvtColor(img, cv2.COLOR_BGR2YCrCb)
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

lower = np.array([0,48,80], dtype="uint8")

upper = np.array([20,255,255], dtype="uint8")

img_hand = cv2.inRange(img_ycrcb,(5, 5, 0), (80, 255, 255))

mask = np.zeros(img.shape).astype(img.dtype)

#경계선 찾음
contours, hierarchy = cv2.findContours(img_hand, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

# 가장 큰 영역 찾기
max = 0
maxcnt = None
for cnt in contours :
    area = cv2.contourArea(cnt)
    if(max < area) :
        max = area
        maxcnt = cnt

color = [255, 255, 255]

# 경계선 내부 255로 채우기

cv2.fillPoly(mask, [maxcnt], color)
img_hand = cv2.bitwise_and(img, mask)
hull = cv2.convexHull(maxcnt)

#cv2.drawContours(mask, [maxcnt],0, (255,255,0), 3)
print(hull)
#cv2.drawContours(mask, [hull],0, (0,255,0), 3)
# rect = cv2.minAreaRect(hull)
# box = cv2.boxPoints(rect)
# box = np.int0(box)
# cv2.drawContours(mask, [box], 0, (0,255,0), 3)

# 정방향의 사각형 그리기  좌측상단의 x,y 좌표/ width / height 값이 도출됨.
x,y,w,h = cv2.boundingRect(hull)
# 도출된 값을 가지고 사각형을 그려줌
cv2.rectangle(mask, (x,y), (x+w,y+h), (0,255,0),3 )




cv2.imshow('image', mask)
#cv2.imshow('image', mask)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

    

[[[ 702  165]]

 [[ 715  166]]

 [[ 792  172]]

 [[ 856  177]]

 [[ 964  186]]

 [[1033  192]]

 [[1041  196]]

 [[1046  201]]

 [[1051  210]]

 [[1052  213]]

 [[1052  224]]

 [[1050  248]]

 [[1022  553]]

 [[1020  558]]

 [[1019  560]]

 [[1015  566]]

 [[1013  568]]

 [[ 846  568]]

 [[ 673  560]]

 [[ 666  559]]

 [[ 662  558]]

 [[ 657  556]]

 [[ 655  555]]

 [[ 644  545]]

 [[ 644  516]]

 [[ 646  486]]

 [[ 666  200]]

 [[ 667  190]]

 [[ 668  184]]

 [[ 672  176]]

 [[ 674  173]]

 [[ 678  170]]

 [[ 683  167]]

 [[ 685  166]]

 [[ 688  165]]]


-1